name: ReleaseBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4 # 建议更新到 v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2 # 建议更新到 v2

    - uses: actions/cache@v4 # 建议更新到 v4
      id: cache
      with:
        path: vcpkg_binary_cache\
        key: ${{ runner.os }}-${{ env.BUILD_CONFIGURATION }}-binarycache-${{ hashFiles('vcpkg.json') }}

    - name: Create vcpkg binary cache directory
      shell: pwsh
      run: |
        $env:VCPKG_DEFAULT_BINARY_CACHE="$env:GITHUB_WORKSPACE\vcpkg_binary_cache"
        New-Item -Type Directory -Force "$env:VCPKG_DEFAULT_BINARY_CACHE"
        echo "VCPKG_DEFAULT_BINARY_CACHE=$env:VCPKG_DEFAULT_BINARY_CACHE" >> $env:GITHUB_ENV

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Vcpkg integrate
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vcpkg integrate install

    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Copy files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: pwsh
      run: |
        .\copyFiles.ps1

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # <-- 主要修改点
      with:
        name: ReleaseBuild
        path: ReleaseBuild\
