name: ReleaseBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  SOLUTION_FILE_PATH: SubtitleFontHelper.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    # 1. 检出主仓库，但明确告诉它不要处理子模块
    - name: Checkout repository (no submodules)
      uses: actions/checkout@v4
      with:
        submodules: false # <-- 禁用自动子模块处理
        fetch-depth: 1    # 主仓库只需要浅克隆

    # 2. (决定性修复) 手动、显式地初始化和更新 vcpkg 子模块
    - name: Manually Initialize and Update vcpkg Submodule
      run: |
        echo "--- Initializing vcpkg submodule ---"
        git submodule init vcpkg
        echo "--- Updating vcpkg submodule (fetching full history) ---"
        # --depth 2147483647 是 Git 中获取完整历史的明确方式
        git submodule update --init --depth 2147483647 vcpkg
        echo "--- vcpkg submodule ready ---"
      shell: pwsh

    # 3. 设置 MSBuild 和 NuGet 工具
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    # 4. 编译 vcpkg 工具自身
    - name: Bootstrap vcpkg
      working-directory: ${{ env.VCPKG_ROOT }}
      run: bootstrap-vcpkg.bat
      shell: cmd

    # 5. 将 vcpkg 添加到 PATH
    - name: Add vcpkg to PATH
      run: echo "${{ env.VCPKG_ROOT }}" >> $env:GITHUB_PATH
      shell: pwsh

    # 6. 还原项目的 NuGet 包
    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    # 7. 使用 vcpkg 安装 C++ 依赖
    - name: Install vcpkg dependencies
      run: |
        vcpkg install --triplet x86-windows-static-md
        vcpkg install --triplet x64-windows-static-md

    # 8. 将 vcpkg 与 MSBuild 集成
    - name: Vcpkg integrate install
      run: vcpkg integrate install

    # 9. 构建项目
    - name: Build x86
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build x64
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    # 10. 复制构建产物
    - name: Copy files
      shell: pwsh
      run: .\copyFiles.ps1

    # 11. 上传构建产物
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ReleaseBuild
        path: ReleaseBuild\
